### ISSUE TITLE
run 404 and Breakpoint is not valid

### ISSUE THREAD

**Issue by happybird100** [Microsoft/remotebuild#11]
iOS 10.1
Now deploy is correct,run 404 and debug 200.
Run on remote  iOS device results in this error:
    DeviceLaunchTimeout
Report by taco-remote-lib --> ios.js   function  runOnDevice
In idevice-app-launcher --> runApp.js function startAppViaDebugger,the third socket message "$c#63" get  answer one character "+". the first message and the seconde message get answer "$OK#9a".
    debug is started and Breakpoint is not valid

**Comment by MSLaguana** [comment]
Does your application have an unusual name? There are limitations to what will work, for example if your application name contains ".app" then we cannot launch it, and I think it had similar symptoms to what you describe above.

The response "+" means "the message was received", but the lack of further response suggests some kind of failure.

**Comment by happybird100** [comment]
I has launch the application.
In idevice-app-launcher --> runApp.js function startApp,use plist to parse xml,get error:
   TypeError: Cannot read property 'nodeValue' of undefined
I think the xml contain gbk or gb2312 character,so i write Regular to find path(Instead of your for):
   var keys = fs.readFileSync(filename, 'utf8');
   var re = new RegExp("/private/var/containers/Bundle/Application/[\\s\\S]{36}/"+packageId+".app","g");
   return keys.match(re)[0];
It works,the application has run by the socket message "$Axxx,0,xxxxxx".
this is a phenomenon you already know?

**Comment by happybird100** [comment]
In iOS 9.3.2(13F69)
debug remote device and local device OK!
after the socket message $c#63,I receive "$Oxxxxxxxxxxxxxxxxxxxxxxxxx#a0",string length 485
I hope this can helpful.

Cordova 6.4.0
XCode 8.1.

**Comment by MSLaguana** [comment]
Can you please clarify what you meant in your previous message? Are you saying that you were able to fix the issue by modifying idevice-app-launcher?

**Comment by happybird100** [comment]
no,I'm not fix all issue.
what i fixed is find app path.the app has launched.
the debug issue still exist in ios10+,ios9.3.2 is ok(remote device and local device).
software versions:Cordova 6.4.0,XCode 8.1,vs2015 update3,mac os 10.11.6

**Comment by MSLaguana** [comment]
I believe that I have published a fix for this in idevice-app-launcher. Please delete `~/.taco_home/node_modules/taco-remote-lib/2.3.0` and re-launch remotebuild and let me know if anything fails.

**Comment by happybird100** [comment]
no,it's not work.

**Comment by MSLaguana** [comment]
Can you please confirm that if you go to `~/.taco_home/node_modules/taco-remote-lib/2.3.0/node_modules/idevice-app-launcher/package.json` it is version 0.1.3?

**Comment by happybird100** [comment]
confirm.
It is version 0.1.3

**Comment by happybird100** [comment]
vs2017 RC fixed this problem
