### ISSUE TITLE
RemoteBuild fails with error message no such file or directory

### ISSUE THREAD

**Issue by jiankai82** [Microsoft/remotebuild#13]
Hi There,

I am using RemoteBuild to build our Cordova project on a remote Mac machine.  Our builds are failing with this error message:

MSBUILD:MSBUILD(0,0): Error : Error: Error: ENOENT: no such file or directory, unlink '/Users/<username>/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/Installing.tmp' 

Can anyone shed some light on how I can fix this issue?  Thanks.

**Comment by MSLaguana** [comment]
Are you able to look at the console where remotebuild is running? What output does it show?

**Comment by MSLaguana** [comment]
Are you also running multiple instances of remotebuild at once?

When we dynamically install packages, we create an `Installing.tmp` file, and when the installation finishes we remove the file. The error you are getting there suggests that the file doesn't exist, but that code path shouldn't be taken unless it created the file earlier on. If you have multiple instances of remotebuild running under the one user, that could be creating a race condition that leads to this issue.

**Comment by jiankai82** [comment]
No, we are just running one instance.  In addition to Installing.tmp file, I also saw these files are also not found from the console log: package.json and tacoRemoteMultiplexer.js.  Here is a snippet from the console log:

Downloading: taco-remote-multiplexer
npm WARN enoent ENOENT: no such file or directory, open '/Users/<username>/.taco_home/node_modules/taco-remote-multiplexer/latest/package.json'
npm WARN latest No description
npm WARN latest No repository field.
npm WARN latest No README data
npm WARN latest No license field.

taco-remote-multiplexer downloaded and installed.
Error: ENOENT: no such file or directory, open '/Users/<username>/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer/tacoRemoteMultiplexer.js'

Downloading: taco-remote-multiplexer
New build request submitted:
/build/tasks?command=build&vcordova=6.2.0&cfg=release&options=--device&loglevel=warn
{"accept-language":"en-US","host":"10.135.8.187:3000","connection":"close","transfer-encoding":"chunked"}

Downloading: taco-remote-multiplexer
/Users/<username>/.taco_home/node_modules/taco-remote-multiplexer/latest
▒~T~T▒~T~@▒~T~@ taco-remote-multiplexer@1.2.9

npm WARN enoent ENOENT: no such file or directory, open '/Users/<username>/.taco_home/node_modules/taco-remote-multiplexer/latest/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/<username>/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer_backup/package.json'

**Comment by MSLaguana** [comment]
The `npm WARN enoent` warnings about missing package.json are benign, they happen because we are `npm install`ing packages to a folder with no package.json which it doesn't expect.

I'm a little confused by why it is downloading `taco-remote-multiplexer` multiple times, or more specifically why it is failing to find part of the contents of it. What version of npm do you have installed? And when did you last try building? I see there that it installed `taco-remote-multiplexer@1.2.9` but the latest version is `1.2.10`, published yesterday.

**Comment by jiankai82** [comment]
We use node version 0.12.7.  You last tried building this morning.

**Comment by MSLaguana** [comment]
I just tried using node 0.12.7 myself and still had no issues.

I'm not sure what's going on for you, but one thing that may help is clearing out the cache that we use. Try turning off remotebuild and then running `rm -r ~/.taco_home/node_modules`. The next time you run remotebuild, it will have to fetch things again, but hopefully clearing the cache will resolve the issue you've hit here.

**Comment by MSLaguana** [comment]
I'm closing this now, but if you're still hitting this after clearing out the node modules cache then please re-open this and we can investigate some more.
