### ISSUE TITLE
Local Deploy install silently fails

### ISSUE THREAD

**Issue by morganabel** [Microsoft/remotebuild#21]
I am having trouble with local debugging. I am trying to debug to a device running 10.2 attached to a windows computer with VS 2015. 

If the app is already installed on the device, it is successfully uninstalled. It says it is successfully installed, but that is not true. I am building using cordova 6.4 and ios 4.3 with automatic provisioning. The device has been added to the Apple developer portal under devices.

Any ideas why the app cannot be installed?

> 1>  ------ Copying back to project: iOS
2>------ Deploy started: Project: Palit, Configuration: Debug iOS ------
2>Found iTunes version: 12.5.4.42
2>Uninstalling app ID:  com.latesnacker.tipt.
2>Successfully installed .ipa file:  C:\Users\morga\OneDrive\Apps\Palit-App\Tipt\bin\iOS\Debug\Palit.ipa.
2>Starting idevicedebugserverproxy.exe at port 3000.
2>Cannot find the app installed on the device. Check that the device is connected, awake, and unlocked.
2>Deployment failed.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by morganabel** [comment]
A potential problem I did notice is that I tried to set iOS device support folder to a local folder on the windows computer. It was mentioned this can work in the docs but maybe I have to manually copy something.

**Comment by MSLaguana** [comment]
The iOS device support folder needs to contain some developer disk images which are provided with xcode. If you manually copy them to your windows machine, then you can point at that, but you can't just point it at an empty folder.

**Comment by morganabel** [comment]
I was thinking that the folder would be populated with something from the Mac. It does not appear that my Xcode installation has these developer disk images in the expected location. Everyone just recommends plugging in your device to install them. Unfortunately I am working with a cloud mac so I can't do that.

How can I get these files if they don't already exist on the Mac (at least not under Applications/Xcode/.../DeviceSupport). The folder doesn't even exist on my Mac installation even though Xcode builds fine.

**Comment by MSLaguana** [comment]
Unfortunately we can't automatically populate things for you. On your mac, can you please try running `xcrun -sdk iphoneos --show-sdk-platform-path`, and then `find <that path> -name "DeveloperDiskImage.dmg"`?

They should be in something like `<path from first command>/DeviceSupport/<version>`, so you should specify the `DeviceSupport` folder in VS' configuration (or copy that whole folder and reference the copy)

**Comment by morganabel** [comment]
I actually found the location, thank you. I am not sure why I couldn't see it any other way, but I was able to find it following these instructions: 

> Go to this Folder Finder > Xcode > Show Package Contents > Developer > Platforms > DeviceSupport.

I am trying to rebuild now and I will close if I can successfully deploy locally. Thank you for the help I appreciate it.

**Comment by morganabel** [comment]
I was finally able to solve it. I am not sure exactly why, but I think I needed to manually create a new development provisioning profile even with the automatic signing. I am not positive this is what made it work but it might be.

**Comment by MSLaguana** [comment]
If your xcode install didn't have the device support library for your particular phone OS, perhaps setting up a provisioning profile caused it to try and communicate with the phone and acquire it? Either way, I'm glad that things seem to be working for you again.
