### ISSUE TITLE
Q: is RESTAPI.md stable?

### ISSUE THREAD

**Issue by compulim** [Microsoft/remotebuild#23]
I am building a [Gulp plugin](https://www.npmjs.com/package/gulp-remotebuild) that trigger `remotebuild` to build a Cordova app, without using MSBuild or Visual Studio. It enables `remotebuild` in a CI/CD workflow (we are using VSTS). It tarball-gzip the input vinyl, send it thru REST to `remotebuild`, then unzip the files back to vinyl.

And I am looking at this [REST API doc](https://github.com/Microsoft/remotebuild/blob/master/src/taco-remote/RESTAPI.md) and its last commit was September 2015.

Is this REST API doc is stable? Are there any upcoming changes to the API?

**Comment by MSLaguana** [comment]
The REST API should be stable, we take backward compatibility seriously.

Have you seen https://github.com/microsoft/taco-cli before? That was a CLI that we provided ourselves which allowed interacting with remotebuild (along with other functionality). You may find that useful for your purposes.

There is also https://github.com/microsoft/vsts-cordova-tasks / https://marketplace.visualstudio.com/items?itemName=ms-vsclient.cordova-extension which is a vsts extension to do cordova builds. It doesn't use remotebuild, but rather the VSTS agent functionality.

**Comment by compulim** [comment]
Great for the tips and the backward compatibility effort!

I looked at `taco-cli` source and I think I will keep the way my Gulp plugin is working (via REST). It is because `taco-cli` is using a physical file system and Gulp prefers `vinyl`, a virtual file system.

Will try out `vsts-cordova-tasks` on my project with my on-premise agent. It simplified so much things.

Thanks!
