### ISSUE TITLE
Can not attach to debug

### ISSUE THREAD

**Issue by gabrielpotumati** [Microsoft/remotebuild#33]
Hello, I'm trying to run the app through the emulator, but after doing the whole process I get this message:

Requesting emulation in iOS Simulator for buildNumber 899 on server http://....:3000/cordova...
http://....:3000/cordova/build/899/emulate?target=iPhone+5 The remote server returned an error: (404) Not Located.
Requesting debugging on remote iOS device to buildNumber 899 on server http://...:3000/cordova...
Debugging - Successfully Debugging on the device
{WebDebugPort = 9221}
Can not attach to debug. Make sure the http://.....:9221 is accessible.
The application you are trying to debug could not be found. Make sure the device is connected, active, and unlocked. Also, make sure that it is with the Web Inspector enabled.

**Comment by AnBucyk** [comment]
Sorry for the delay on this, we're very shorthanded right now. 

This looks like you forgot to set the IP to your remotebuild server in Visual Studio. Tools -> Options -> Tools for Apache Cordova -> iOS Configuration. Enter the Host and Port for your remotebuild server, make sure "Enable remote iOS processing" is set to true.

**Comment by dmitrii-snytkin** [comment]
The bug reproduces.
