### ISSUE TITLE
IOS Icons

### ISSUE THREAD

**Issue by gabrielpotumati** [Microsoft/remotebuild#36]
Hello, when compiling the app for android the icons appear correctly, however when compiling for IOS does not appear the custom icons, it comes with the standard icons of the cordova.
Anyone know how to solve this?

**Comment by dmitriy-petrishin** [comment]
Hi @gabrielpotumati.

Unfortunately, this is a topic about remote build but not about Cordova-cli.
But, anyway, I would like to suggest you read [that](https://cordova.apache.org/docs/en/latest/config_ref/images.html) paragraph about icons in cordova.

Hope, that will help.
