### ISSUE TITLE
Cordova IOS debug and runtime issues

### ISSUE THREAD

**Issue by ekambarrao** [Microsoft/remotebuild#37]
Hi, I have been fighting to build and deploy cordova application to IOS platform since last 30 days using visual studio 2017 and macincloud.

I am unable to find any replies to all my postings in stackoverflow, here and in visual studio community as well.

Am I the only person having this problem or everybody have this problem.

There are multiple issues and I am unable to figure out if the problem is 

visual studio
cordova
xcode
remotebuild
macincloud

remotebuild debug set up

or what else!!!

Problem details are at the following link.

https://developercommunity.visualstudio.com/content/problem/61875/visual-studio-2017-cordova-ios-debug-on-local-devi.html

any help would be great breakthrough for me.

thx

**Comment by dmitriy-petrishin** [comment]
Hi there, sorry for late answer.

I saw you've figured out with that problem by yourself, nice to see.
What about new improvements with xcode - I guess this information might be reflected in apple documentation.

Anyway thanks for reporting the issue, I close it. 
Feel free to report new issues if you have them.
