### ISSUE TITLE
Your build may fail if the version installed is 8.0 or greater

### ISSUE THREAD

**Issue by jonathangraci** [Microsoft/remotebuild#38]
Hi, I'm trying to compile my app using Visual Studio 2015 and XCode 8.3.2.

I have this need to use plugins that need XCode 8+

The compilation gives me the error: MSBUILD: cordova-build error: Error: Remote build error from build server Build failed with error Command to fetch XCode version failed. Your build may fail if the version installed is 8.0 or higher. - 1

You can help me?

**Comment by AnBucyk** [comment]
Sorry for the delay on this.

If you're getting this error message, it means our ability to fetch your XCode version number failed. If it fails in this way, we have no way of telling if you have an incompatible combination of XCode and cordova-ios.

Ensure your cordova-ios version is 4.3.0 or greater, then try again.

**Comment by Webrusterkk** [comment]
getting Same issue on updating the Xcode to  9.1

**Comment by pietrobr** [comment]
getting the same issue with vs 2017 and xcode 9.2
