### ISSUE TITLE
Error with xcode 8.3

### ISSUE THREAD

**Issue by braidiano** [Microsoft/remotebuild#39]
using cordova-ios 4.3.0 and xcode 8.3 is no longer possible to compile:

1>  “Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
1>  “Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
1>
1>  ** ARCHIVE FAILED **

**Comment by AnBucyk** [comment]
Sounds like you're using a plugin that uses Swift, but doesn't use the latest version. IIRC, you need to set something in one of the ios project files for the plugin. Regardless, this sounds like an issue with your project, not one with remotebuild. We aren't going to enforce a version of Swift for projects using remotebuild.

Feel free to reopen this is you can confirm it's an issue with remotebuild and not one with your project.
