### ISSUE TITLE
No longer able to build app for iOS platform

### ISSUE THREAD

**Issue by ZaLiTHkA** [microsoft/remotebuild#46]
Greetings,

I've been fighting with this same issue for a little over a week now and I'm no closer to getting it working. I need to get around this so that I can work at debugging a completely different problem in our code, but I can't even get to that until I can run the app again.

The last few lines I see in VS2015's "Build" output are as follows:

```
1>  The following build commands failed:
1>  	CodeSign /Users/macmini/Library/Developer/Xcode/DerivedData/DU_Diagnostics-hbnmbepzehdebhdggxgfxzmtdiff/Build/Intermediates/ArchiveIntermediates/DU\ Diagnostics/InstallationBuildProductsLocation/Applications/DU\ Diagnostics.app
1>  (1 failure)
1>  Failed to build app for buildNumber 10922: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/macmini/.taco_home/remote-builds/taco-remote/builds/10922/cordovaApp/platforms/ios/cordova/build-debug.xcconfig,-workspace,DU Diagnostics.xcworkspace,-scheme,DU Diagnostics,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,DU Diagnostics.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/macmini/.taco_home/remote-builds/taco-remote/builds/10922/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/macmini/.taco_home/remote-builds/taco-remote/builds/10922/cordovaApp/platforms/ios/build/sharedpch
1>MSBUILD : cordova-build error : Error: Remote build error from the build server Build failed with error Error code 65 for command: xcodebuild with args: -xcconfig,/Users/macmini/.taco_home/remote-builds/taco-remote/builds/10922/cordovaApp/platforms/ios/cordova/build-debug.xcconfig,-workspace,DU Diagnostics.xcworkspace,-scheme,DU Diagnostics,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,DU Diagnostics.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/macmini/.taco_home/remote-builds/taco-remote/builds/10922/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/macmini/.taco_home/remote-builds/taco-remote/builds/10922/cordovaApp/platforms/ios/build/sharedpch - 1
1>  Error Remote build error from the build server Build failed with error Error code 65 for command: xcodebuild with args: -xcconfig,/Users/macmini/.taco_home/remote-builds/taco-remote/builds/10922/cordovaApp/platforms/ios/cordova/build-debug.xcconfig,-workspace,DU Diagnostics.xcworkspace,-scheme,DU Diagnostics,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,DU Diagnostics.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/macmini/.taco_home/remote-builds/taco-remote/builds/10922/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/macmini/.taco_home/remote-builds/taco-remote/builds/10922/cordovaApp/platforms/ios/build/sharedpch - {1}
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

I honestly can't remember the finer details of all the steps I've taken to try get around this issue, but I can try summarise them for reference. Some of them have also resulted in my breaking other steps in the process, each of which I've managed to resolve thereafter:

* Build process constantly trying to reinstall `taco-remote-multiplexer`
* Build process unable to find `taco-remote-lib`
* A few others that I can't remember now..

After all of this, I am still left with the error message posted above. I have saved the entire build output log to [this gist](https://gist.github.com/ZaLiTHkA/70adf6ddf0e4799173f2425cf4f98f6a) for reference (hopefully there's nothing sensitive in this output, I haven't modified or masked anything).. I'm hoping someone can make sense of it.

---

My environment is currently as follows:

* Windows 10 Pro x64 with latest updates
* VS2015 Community 14.0.25431.01 Update 3
Visual Studio Tools for Apache Cordova Update 10
* Mac OSX El Capitan 10.11.6
* xCode 8.2.1

With regards to what I've tried here, I'll start off with the more recent ones, because they're either more fresh in my mind or (from those tried this morning) I still have the tabs open. Some of these have been in aid of trying to fix other things that I broke (as mentioned above), but this should give you an idea of how desperate I am to get this working...

* Tried all suggestions [here](https://github.com/Microsoft/remotebuild/issues/26),[here](https://github.com/Microsoft/remotebuild/issues/5) and [here](https://github.com/Microsoft/remotebuild/issues/8) (because I was seeing this behaviour anyway)
* Completely removed and reinstalled `remotebuild` on my Mac
* Completely removed and reinstalled NodeJS itself, using latest of version 4 and 6 ranges
* The suggestions posted [here](https://stackoverflow.com/questions/39501020/code-sign-error-on-xcode-8-and-ios-10-cordova-project), because of the error I see when trying to run `remotebuild test`
* Completed all steps listed in the Taco [iOS Guide](http://taco.visualstudio.com/en-us/docs/ios-guide/), at least twice.
* Regenerated and redeployed all provisioning profiles (and therefore certificates, etc..)
* Tried using Cordova 6.5.0 and 7.0.1, both on my local PC and the remote Mac
* Removed and reinstalled VS2015 (..and my god did this take forever)
* Using custom NodeJS, including forcing the fact by adding my custom path before the others in VS2015's "Options > Projects and Solutions > External Web Tools"

I have now spent over 40 hours trying to fix this one god damn &%#$Z^$*@!@%$ing issue. Please can somebody help me out? Every Google search I try shows a list of pages I've already visited, I'm so lost I don't know where to go next..

**Edit:** Almost forgot one other important aspect, the different changes I've tried in the iOS section of my `build.json` file... These include:

* both with and without a `provisioningProfile` key
* both with and without `packageType` key, as `development` and `ad-hoc`

**Comment by ZaLiTHkA** [comment]
..and now I need to go for a dentist appointment. So if anybody has any suggestions on this issue, please pass them on and I'll get back to this either later this afternoon or first thing tomorrow morning (GMT+2 for me).

Thanks in advance.

**Comment by ZaLiTHkA** [comment]
So this is suddenly far less important now. I've moved our entire project over to a much nicer workflow using the Adobe PhoneGap tools. :)

I am still curious as to what might be the issue here, but if it's still unresolved in a week's time, I'll happily close this issue, ditch VS2015 completely and be content with a simpler life.

**Comment by hoostcom** [comment]
Find a solution to that @ZaLiTHkA ?

**Comment by ZaLiTHkA** [comment]
@hoostcom, nope, unfortunately I did not.. These days we've moved our mobile dev completely over to Ionic, building the Android `apk` binaries locally on our Windows machines and the iOS `ipa` binaries with Ionic Package.

thanks for the reminder that this issue was still open though, I haven't even thought about this one in ages...
