### ISSUE TITLE
7.0.1 is an invalid cordova version

### ISSUE THREAD

**Issue by WilliamVenner** [Microsoft/remotebuild#49]
**What I'm trying to do:**

Use `remotebuild` to build my Cordova app remotely from `taco-cli` on my Windows machine.

**What I've done:**

(On Mac)

```
sudo npm install cordova@7.0.1 cordova-ios@4.5.0 remotebuild -g
remotebuild start
```

(On Windows)

```
cd projectfolder
npm install cordova@7.0.1 cordova-ios@4.5.0 taco-cli -g
taco build ios
```

**What happens:**

Upon running `taco build ios` on my Windows machine, it sends all the data to my Mac, begins to build and then fails with this `build.log`:

```
/Users/admin/.taco_home/node_modules/taco-remote-lib/2.3.2/node_modules/taco-utils/tacoPackageLoader.js:274
                    throw errorHelper.get(TacoErrorCodes.PackageLoaderInvalidPackageVersionSpecifier, packageId.split("@")[1], packageName);
                    ^
PackageLoaderInvalidPackageVersionSpecifier: Error: 7.0.1
 is an invalid cordova version
Process exited with code 1
```

**Comment by ntheile** [comment]
++

**Comment by c0r3yz** [comment]
Has there been any resolution here? I'm having the same issue.

**Comment by c0r3yz** [comment]
Just to add to this issue, I tried removing ios from the project and adding it back in at the correct version:

`taco platform rm ios`

After that's successful...

`taco platform add ios@4.5.0`

Still getting the same error...

**Comment by Trecobat** [comment]
In your project's root, add a file named taco.json and add in:  
```
{
  "cordova-cli": "7.0.1"
}
```
Then `taco build ios`
