### ISSUE TITLE
Build failed with error Warning: Could not find development team.

### ISSUE THREAD

**Issue by NormTheThird** [Microsoft/remotebuild#51]
Having issues with my build.json not working.  Not sure if this is an issue of remote build but its giving me this issue.  Im using Visual Studio 2017, Cordova 7.1.0, ios platform 4.5.2

1>MSBUILD : cordova-build error : Remote build error from the build server http://25.110.24.226:3000/cordova - Build failed with error Warning: Could not find development team. Starting with XCode 8, you must provide a build.json with a development team. See https://go.microsoft.com/fwlink/?linkid=833112 for more details.

Here is my build.json code.

{
  "android": {
    "release": {
      "keystore": "",
      "storePassword": "",
      "alias": "",
      "password": "",
      "keystoreType": ""
    }
  },

  "ios": {
    "debug": {
      "codeSignIdentity": "iPhone Developer",
      "developmentTeam": "253T5B4P9B",
      "packageType": "development",
      "provisioningProfile": "1334738f-4466-4fb9-b485-87615af06c74"
      //"buildFlag": [
      //  "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
      //  "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
      //  "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\""
      //]
    },

    "release": {
      "developmentTeam": "253T5B4P9B",
      "codeSignIdentity": "iPhone Developer",
      "packageType": "app-store",
      "provisioningProfile": "1334738f-4466-4fb9-b485-87615af06c74"
    }
  }
}

**Comment by NormTheThird** [comment]
Got this working

**Comment by samharshsoftware** [comment]
++NormTheThird we are facing same issue , Please suggest how got this working 
Im using Visual Studio 2017, Cordova 7.1.0, ios platform 4.5.2

Warning: Could not find development team. Starting with XCode 8, you must provide a build.json with a development team. See https://go.microsoft.com/fwlink/?linkid=833112 for more details.
