### ISSUE TITLE
Problems installing taco-remote-multiplexer

### ISSUE THREAD

**Issue by claudiosvcc** [Microsoft/remotebuild#8]
Hi, can you please try to give some light on this?
This problem is happening intermittently.
When a build request arrives, I can see this in logs:

`New build request submitted:
/build/tasks?command=build&vcordova=6.2.0&cfg=debug&options=--device&loglevel=warn
{"accept-language":"en-US","host":"<MyHost>","connection":"close","transfer-encoding":"chunked"}

Downloading: taco-remote-multiplexer
^[[0mGET /cordova/build/tasks/17420 ^[[32m200 ^[[0m0.629 ms - 770^[[0m
npm WARN enoent ENOENT: no such file or directory, open '/Users/<MyUSer>/.taco_home/node_modules/taco-remote-multiplexer/latest/package.json'
npm WARN latest No description
npm WARN latest No repository field.
npm WARN latest No README data
npm WARN latest No license field.

taco-remote-multiplexer downloaded and installed.
Error: ENOENT: no such file or directory, open '/Users/<MyUser>/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer/tacoRemoteMultiplexer.js'`

Indeed the package.json is not there, but the tacoRemoteMultiplexer.js is.

Any ideas on how to fix this?

**Comment by MSLaguana** [comment]
This is part of our "auto-updating" mechanism to make allow remotebuild to pick up fixes dynamically. Every ~ 4 hours it will attempt to fetch the latest version of `taco-remote-multiplexer`, which is what you see happening here. The warning about a missing package.json is not significant, we are running `npm install taco-remote-multiplexer` from inside that `.../latest/` folder, and npm is checking to see if there is a package.json that it should read, thinking that it is a project.

The other error reported there I haven't yet had the opportunity to investigate deeply, but it shouldn't have an impact on anything apart from the error log you see there. As you mention, the file does exist whenever I try to find it, and builds have always functioned normally when I look at it so while I'm not sure of the exact cause, it does not seem to impact functionality.

**Comment by claudiosvcc** [comment]
I see, but actually on windows side the agent is failing. Here is the output:

##[error]MSBUILD(0,0): Error : Error: TACO0208: Error attempting to recover from failed installation at /Users/<>/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer. 
## [error]MDAVSCLI(0,0): Error TACO0208: Error attempting to recover from failed installation at /Users/<>/.taco_home/node_modules/taco-remote-multiplexer/latest/node_modules/taco-remote-multiplexer. 
##[error]MSBUILD(0,0): Error : Inner Error: 
MSBUILD : cordova-build error : Inner Error: 
##[error]EXEC(0,0): Error (TaskId: 7)
139>EXEC : Inner error (TaskId: 7)  
##[error]MSBUILD(0,0): Error : ENOENT: no such file or directory, rename 

[ .... Same message I've sent before ... ]

Done executing task "MdaVsCli" -- FAILED. (TaskId:7)
2016-10-28T02:06:46.2219376Z          Done building target "BuildMDA" in project "<>.jsproj" -- FAILED.: (TargetId:10)
2016-10-28T02:06:46.2219376Z          Done Building Project "C:\BuildAgent\_work\1\s\src\<>\exe\<>.jsproj" (Build target(s)) -- FAILED.
2016-10-28T02:06:46.2219376Z          Deferred Messages

Indeed seems the update warning, although showing almost every build, are not correlated with failures. Any info I can grab to help you?

**Comment by MSLaguana** [comment]
Ah yes, that is more serious. That `TACO0208` error happens when we try to download an updated version of `taco-remote-lib`, it fails, and we also fail to roll back to the previous version.

I'm not sure what the specific error you're hitting is, but I would suggest going to your mac running remotebuild, shut down remotebuild, run `rm -r ~/.taco_home/node_modules`, then start up remotebuild again. That will clear out all the caches we have, and hopefully get things working again. If that fails, we'll have to investigate further.

**Comment by claudiosvcc** [comment]
The solution you gave me seems to work.
Thanks!
